security:
  basic:
    enabled: true
  user:
    name: server-zuul
    password: 35446Q3QJS7UvVdN
server:
  port: 6020
eureka:
  client:
    serviceUrl:
      defaultZone: http://server-eureka:2lvoHcfXbXmTBvQm@localhost:6000/eureka
  instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
logging:
  config: classpath:logback.xml
spring:
  application:
    name: hrym-server-zuul
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
#禁用SendErrorFilter过滤器，此过滤器会跳转错误页面，导致结果输出不了
#SendErrorFilter里面的dispatcher.forward(request, ctx.getResponse())会启用writer，导致post里面write返回结果的时候报错：
#Java.lang.IllegalStateException: getWriter() has already been called for this response
zuul:
  routes:
    yjy-application-base:
      path: /base/**
      stripPrefix: false
    yjy-application-user:
      path: /user/**
      stripPrefix: false
    yjy-application-common:
      path: /common/**
      stripPrefix: false
    yjy-application-app:
      path: /app/**
      stripPrefix: false
    yjy-application-wechat:
      path: /wechat/**
      stripPrefix: false
    yjy-application-payment:
      path: /pay/**
      stripPrefix: false
    yjy-application-service:
      path: /service/**
      stripPrefix: false
    yjy-application-third:
      path: /third/**
      stripPrefix: false
    yjy-application-doctor:
      path: /doctor/**
      stripPrefix: false
    yjy-application-operation:
      path: /operation/**
      stripPrefix: false
    yjy-application-trade:
      path: /trade/**
      stripPrefix: false
    yjy-application-shop:
      path: /shop/**
      stripPrefix: false
    yjy-application-crm:
      path: /crm/**
      stripPrefix: false
    operation-api:
      path: /operationv2/**
      stripPrefix: false
  SendErrorFilter:
    error:
      disable:
        true
  sensitive-headers: "*"

#配置超时时间，断点调试，上传大文件等容易超时
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000



