server:
  port: 8083
spring:
  application:
    name: hrym-provider-user
  autoconfigure:
      exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
logging:
  level:
    org:
      springframework:
        web: DEBUG


