server:
  port: 5588

spring:
  application:
    name: hyrm-config-server
  cloud:
    config:
      server:
        git:
          uri: http://123.58.37.93:9900/root/hrym-config-server.git #配置Git仓库位置。
          searchPaths: config-repo #配置仓库路径下的相对搜索位置，可以配置多个。
          username: hrym_env #访问 Git 仓库的用户名。
          password: hrym201809 #访问 Git 仓库的用户密码。
          label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

