server:
  port: 5588

spring:
  application:
    name: hyrm-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codejyhuang/hrym-config.git #配置Git仓库位置。
          searchPaths: config #配置仓库路径下的相对搜索位置，可以配置多个。
          username: codejyhuang #访问 Git 仓库的用户名。
          password: ann863+-hjy.. #访问 Git 仓库的用户密码。
          label: master #配置仓库的分支
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin-test:Hrym201809@localhost:8761/eureka/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

