server:
  port: 8085
spring:
  application:
    name: hrym-provider-pray
  autoconfigure:
      exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml


