server:
  port: 8081
spring:
  application:
    name: hrym-application-hgx
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#配置超时时间，断点调试，上传大文件等容易超时
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 600000



