server:
  port: 8084
spring:
  application:
    name: hrym-provider-flock
  autoconfigure:
      exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml


