spring:
  application:
    name: hrym-server-eureka
security:
  basic:
    enabled: true
  user:
    name: server-eureka
    password: 2lvoHcfXbXmTBvQm
logging:
  config: classpath:logback.xml

server:
  port: 6000
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
  server:
    enable-self-preservation: false
endpoints:
  shutdown:
    enabled: true
    sensitive: false





